# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:10.16.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      # We have to reinstall Cypress because of this issue: https://github.com/cypress-io/cypress/issues/2344
      - run: yarn cypress install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
            - /root/.cache/Cypress
          key: v1-dependencies-{{ checksum "package.json" }}

      # run integration / unit tests
      - run: yarn test

      - run: yarn start & yarn wait-on http://localhost:3000 && curl -sS http://localhost:3000 && yarn cypress run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots